In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
type(arr)

numpy.ndarray

In [6]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [7]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [10]:
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [11]:
type(arr)

numpy.ndarray

In [13]:
arr.T

array([[[1],
        [4],
        [7]],

       [[2],
        [5],
        [8]],

       [[3],
        [6],
        [9]]])

In [14]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [17]:
a.max()

9

In [18]:
a.min()

1

In [19]:
a.mean()

5.0

In [20]:
a.shape

(3, 3)

In [21]:
# (20,6)

a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.where(a>4)

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

In [23]:
np.where(a%2==0)

(array([0, 1, 1, 2], dtype=int64), array([1, 0, 2, 1], dtype=int64))

In [25]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [26]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [28]:
b = np.where(a>4)

In [29]:
a[b]

array([5, 6, 7, 8])